package com.evan.chat.data.source.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.evan.chat.data.source.model.Chat;
import com.evan.chat.data.source.model.Friend;
import com.evan.chat.data.source.model.User;
import com.evan.chat.data.source.model.Setting;
import com.evan.chat.data.source.model.Classify;

import com.evan.chat.data.source.dao.ChatDao;
import com.evan.chat.data.source.dao.FriendDao;
import com.evan.chat.data.source.dao.UserDao;
import com.evan.chat.data.source.dao.SettingDao;
import com.evan.chat.data.source.dao.ClassifyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatDaoConfig;
    private final DaoConfig friendDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig settingDaoConfig;
    private final DaoConfig classifyDaoConfig;

    private final ChatDao chatDao;
    private final FriendDao friendDao;
    private final UserDao userDao;
    private final SettingDao settingDao;
    private final ClassifyDao classifyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatDaoConfig = daoConfigMap.get(ChatDao.class).clone();
        chatDaoConfig.initIdentityScope(type);

        friendDaoConfig = daoConfigMap.get(FriendDao.class).clone();
        friendDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        settingDaoConfig = daoConfigMap.get(SettingDao.class).clone();
        settingDaoConfig.initIdentityScope(type);

        classifyDaoConfig = daoConfigMap.get(ClassifyDao.class).clone();
        classifyDaoConfig.initIdentityScope(type);

        chatDao = new ChatDao(chatDaoConfig, this);
        friendDao = new FriendDao(friendDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        settingDao = new SettingDao(settingDaoConfig, this);
        classifyDao = new ClassifyDao(classifyDaoConfig, this);

        registerDao(Chat.class, chatDao);
        registerDao(Friend.class, friendDao);
        registerDao(User.class, userDao);
        registerDao(Setting.class, settingDao);
        registerDao(Classify.class, classifyDao);
    }
    
    public void clear() {
        chatDaoConfig.clearIdentityScope();
        friendDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        settingDaoConfig.clearIdentityScope();
        classifyDaoConfig.clearIdentityScope();
    }

    public ChatDao getChatDao() {
        return chatDao;
    }

    public FriendDao getFriendDao() {
        return friendDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public SettingDao getSettingDao() {
        return settingDao;
    }

    public ClassifyDao getClassifyDao() {
        return classifyDao;
    }

}
